### ISSUE TITLE
Phone auth plus options

### ISSUE THREAD

**Issue by MetaBureau** [ncwoehler/nuxt-firebaseui-starter#1]
Hello & thank you for your project.
I can enable phone auth easily (  Phone: firebase.auth.PhoneAuthProvider.PROVIDER_ID ) but do not understand where to set configuration options such as default country. Are you able to assist?

**Comment by ncwoehler** [comment]
This template uses the Firebase UI library. Here's a detailed documentation on how to setup the authentication: https://github.com/firebase/firebaseui-web#using-firebaseui-for-authentication
