### ISSUE TITLE
Implement OAuthProvider suchas Apple or Microsoft

### ISSUE THREAD

**Issue by MetaBureau** [ncwoehler/nuxt-firebaseui-starter#2]
What is the correct way to use OAuth in this project?

EG: firebase.auth.OAuthProvider('apple.com')

**Comment by ncwoehler** [comment]
You can configure the Firebase Auth UI here: https://github.com/ncwoehler/nuxt-firebaseui-starter/blob/master/components/FirebaseUI.vue#L19

It uses the FirebaseUI package so a detailed explanation on how to configure it can be found here: https://github.com/firebase/firebaseui-web#using-firebaseui-for-authentication
