### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by edeuxk** [ncwoehler/nuxt-firebaseui-starter#3]
Hello!

Thanks for sharing your boilerplate, it's very interesting.
I have a question, how can I change the language for the firebase-ui?
I've check the doc but it doesn't work with Nuxt

**Comment by ncwoehler** [comment]
This starter project uses the npm module of the firebaseui-web library. You would need to change it to use the library via CDN as explained here: https://github.com/firebase/firebaseui-web#localized-widget
